// <auto-generated />
using AndreiBrindusan.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AndreiBrindusan.DataModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230821144834_Weights")]
    partial class Weights
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AndreiBrindusan.DataModel.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepotId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("DepotId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.Depot", b =>
                {
                    b.Property<string>("DepotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepotId");

                    b.ToTable("Depot");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.DrugType", b =>
                {
                    b.Property<string>("DrugTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DrugTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DrugTypeId");

                    b.ToTable("DrugType");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.DrugUnit", b =>
                {
                    b.Property<string>("DrugUnitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepotId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DrugUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PickNumber")
                        .HasColumnType("int");

                    b.HasKey("DrugUnitId");

                    b.HasIndex("DrugTypeId");

                    b.ToTable("DrugUnit");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.Country", b =>
                {
                    b.HasOne("AndreiBrindusan.DataModel.Depot", "Depot")
                        .WithMany("Countries")
                        .HasForeignKey("DepotId");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.DrugUnit", b =>
                {
                    b.HasOne("AndreiBrindusan.DataModel.DrugType", "DrugType")
                        .WithMany()
                        .HasForeignKey("DrugTypeId");

                    b.Navigation("DrugType");
                });

            modelBuilder.Entity("AndreiBrindusan.DataModel.Depot", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
